# Generated by Django 3.1 on 2020-09-01 21:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20200901_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(verbose_name='What Is Your Mind ...?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=264, unique=True),
        ),
    ]
