# Generated by Django 3.1 on 2020-09-02 00:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_auto_20200902_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='What Is Your Mind ...?'),
        ),
    ]
