# Generated by Django 3.1 on 2020-08-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/media/profile_pics/profile.png', upload_to='profile_pics'),
        ),
    ]
