# Generated by Django 3.1 on 2020-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_auto_20200829_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.png', upload_to='profile_pics'),
        ),
    ]
