# Generated by Django 3.1 on 2020-08-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0011_auto_20200829_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pics/profile_pic.png', null=True, upload_to='profile_pics'),
        ),
    ]
