# Generated by Django 3.1 on 2020-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0012_auto_20200829_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/profile_pic.png', upload_to='profile_pics', verbose_name=''),
        ),
    ]
